"""
PostgreSQL / Supabase Schema Migrator and Database Manager
Connects via DATABASE_URL to automatically create all e-commerce, delivery,
vendor, rider, customer, inventory, review, and tracking tables.
"""
import os
import sys
import json
import urllib.parse
from datetime import datetime

# Try importing PostgreSQL drivers
_has_psycopg2 = False
_has_pg8000 = False

try:
    import psycopg2
    from psycopg2 import sql
    from psycopg2.extras import RealDictCursor
    _has_psycopg2 = True
except ImportError:
    pass

try:
    import pg8000.native
    _has_pg8000 = True
except ImportError:
    pass

def get_database_url():
    """Retrieves and normalizes DATABASE_URL from environment."""
    url = (
        os.getenv("DATABASE_URL")
        or os.getenv("POSTGRES_URL")
        or os.getenv("POSTGRESQL_URL")
        or os.getenv("SUPABASE_DB_URL", "")
    ).strip()
    return url

def get_postgres_connection():
    """
    Establishes a connection to PostgreSQL using psycopg2 or pg8000.
    Returns (connection, driver_name) or (None, error_str).
    """
    db_url = get_database_url()
    if not db_url:
        return None, "DATABASE_URL environment variable is not set."

    # Fix potential postgres:// vs postgresql:// prefix
    normalized_url = db_url
    if normalized_url.startswith("postgres://"):
        normalized_url = "postgresql://" + normalized_url[len("postgres://"):]

    # 1. Try psycopg2 if installed
    if _has_psycopg2:
        try:
            # Ensure sslmode requirement for Supabase / Cloud hosts
            conn_dsn = normalized_url
            if "sslmode" not in conn_dsn and "@" in conn_dsn:
                separator = "&" if "?" in conn_dsn else "?"
                conn_dsn = f"{conn_dsn}{separator}sslmode=require"

            conn = psycopg2.connect(conn_dsn)
            conn.autocommit = True
            return conn, "psycopg2"
        except Exception as err:
            psycopg2_err = str(err)
            print(f"⚠️ [postgres_migrator] psycopg2 connection failed: {psycopg2_err}")
            # Try plain URL without appending sslmode if it caused parse issues
            try:
                conn = psycopg2.connect(normalized_url)
                conn.autocommit = True
                return conn, "psycopg2"
            except Exception:
                pass

    # 2. Try pg8000 pure-python driver if available
    if _has_pg8000:
        try:
            parsed = urllib.parse.urlparse(normalized_url)
            import ssl
            ssl_ctx = ssl.create_default_context()
            ssl_ctx.check_hostname = False
            ssl_ctx.verify_mode = ssl.CERT_NONE

            conn = pg8000.native.Connection(
                user=urllib.parse.unquote(parsed.username or "postgres"),
                password=urllib.parse.unquote(parsed.password or ""),
                host=parsed.hostname or "localhost",
                port=parsed.port or 5432,
                database=parsed.path.lstrip("/") or "postgres",
                ssl_context=ssl_ctx
            )
            return conn, "pg8000"
        except Exception as pg_err:
            print(f"⚠️ [postgres_migrator] pg8000 connection failed: {pg_err}")

    driver_status = f"Drivers available: psycopg2={_has_psycopg2}, pg8000={_has_pg8000}"
    return None, f"No working PostgreSQL driver found or connection failed. {driver_status}"

# List of 14 production/experiment tables
TABLES_METADATA = [
    {"name": "users", "desc": "Telegram bot users, phone & uploaded profile pictures"},
    {"name": "vendors", "desc": "Vendor & Merchant shop directory"},
    {"name": "riders", "desc": "Delivery Rider list, vehicles & availability"},
    {"name": "customers", "desc": "Customer contact list & order metrics"},
    {"name": "categories", "desc": "Product Categories & icons"},
    {"name": "products", "desc": "E-Commerce Product catalog & prices"},
    {"name": "orders", "desc": "Customer orders & fulfillment status"},
    {"name": "order_items", "desc": "Order item details & quantities"},
    {"name": "delivery_tracking", "desc": "Live delivery tracking & coordinates"},
    {"name": "payments", "desc": "Payment transactions & methods (COD, bKash, etc.)"},
    {"name": "reviews", "desc": "Customer reviews & 5-star ratings for shops & riders"},
    {"name": "coupons", "desc": "Promo discount codes & campaign rules"},
    {"name": "notifications", "desc": "System alerts & Telegram notification queue"},
    {"name": "audit_logs", "desc": "System activity logs & data change history"}
]

SQL_CREATE_ALL_TABLES = """
-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    image_name TEXT NOT NULL,
    image_url TEXT NOT NULL,
    telegram_id TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Vendors Table
CREATE TABLE IF NOT EXISTS public.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT DEFAULT '',
    address TEXT DEFAULT '',
    commission_pct NUMERIC DEFAULT 10.0,
    status TEXT DEFAULT 'active',
    rating NUMERIC DEFAULT 5.0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Riders Table
CREATE TABLE IF NOT EXISTS public.riders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    vehicle_type TEXT DEFAULT 'Motorbike',
    vehicle_plate TEXT DEFAULT '',
    status TEXT DEFAULT 'available',
    current_lat NUMERIC DEFAULT 23.8103,
    current_lng NUMERIC DEFAULT 90.4125,
    rating NUMERIC DEFAULT 5.0,
    total_deliveries INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id TEXT DEFAULT '',
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT DEFAULT '',
    address TEXT DEFAULT '',
    total_orders INT DEFAULT 0,
    loyalty_points INT DEFAULT 0,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE,
    description TEXT DEFAULT '',
    icon TEXT DEFAULT '🛍️',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    category TEXT DEFAULT 'General',
    price NUMERIC NOT NULL,
    cost_price NUMERIC DEFAULT 0.0,
    stock INT DEFAULT 100,
    sku TEXT DEFAULT '',
    image_url TEXT DEFAULT '',
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE SET NULL,
    rider_id BIGINT REFERENCES public.riders(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    delivery_address TEXT DEFAULT '',
    total_price NUMERIC DEFAULT 0.0,
    delivery_fee NUMERIC DEFAULT 0.0,
    discount NUMERIC DEFAULT 0.0,
    status TEXT DEFAULT 'pending',
    payment_status TEXT DEFAULT 'unpaid',
    payment_method TEXT DEFAULT 'Cash on Delivery',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_title TEXT NOT NULL,
    quantity INT DEFAULT 1,
    unit_price NUMERIC DEFAULT 0.0,
    total_price NUMERIC DEFAULT 0.0
);

-- 9. Delivery Tracking Table
CREATE TABLE IF NOT EXISTS public.delivery_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    rider_id BIGINT REFERENCES public.riders(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'assigned',
    current_location TEXT DEFAULT '',
    latitude NUMERIC DEFAULT 23.8103,
    longitude NUMERIC DEFAULT 90.4125,
    estimated_delivery TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '45 minutes'),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Payments Table
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    transaction_id TEXT UNIQUE,
    payment_method TEXT DEFAULT 'Cash on Delivery',
    amount NUMERIC NOT NULL,
    currency TEXT DEFAULT 'BDT',
    status TEXT DEFAULT 'completed',
    gateway_response JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE SET NULL,
    rider_id BIGINT REFERENCES public.riders(id) ON DELETE SET NULL,
    rating INT DEFAULT 5,
    comment TEXT DEFAULT '',
    review_type TEXT DEFAULT 'shop',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Coupons Table
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_pct NUMERIC DEFAULT 10.0,
    discount_flat NUMERIC DEFAULT 0.0,
    min_order_value NUMERIC DEFAULT 100.0,
    max_discount NUMERIC DEFAULT 500.0,
    valid_until TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 days'),
    usage_limit INT DEFAULT 1000,
    times_used INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_type TEXT DEFAULT 'customer',
    recipient_id TEXT DEFAULT '',
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    channel TEXT DEFAULT 'telegram',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name TEXT NOT NULL,
    entity_id TEXT DEFAULT '',
    action TEXT NOT NULL,
    details JSONB DEFAULT '{}'::jsonb,
    performed_by TEXT DEFAULT 'system',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
"""

SQL_POLICIES_AND_BUCKET = """
-- Enable Row Level Security (RLS) & Public Policies for all 14 tables
DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'users', 'vendors', 'riders', 'customers', 'categories',
        'products', 'orders', 'order_items', 'delivery_tracking',
        'payments', 'reviews', 'coupons', 'notifications', 'audit_logs'
    ];
BEGIN
    FOREACH tbl IN ARRAY tables LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = format('Public Access for %s', tbl)
        ) THEN
            EXECUTE format('CREATE POLICY "Public Access for %s" ON public.%I FOR ALL USING (true) WITH CHECK (true);', tbl, tbl);
        END IF;
    END LOOP;
END $$;

-- Storage Bucket: 'user-images' & Public Policies (if storage schema exists)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'storage') THEN
        INSERT INTO storage.buckets (id, name, public)
        VALUES ('user-images', 'user-images', true)
        ON CONFLICT (id) DO UPDATE SET public = true;

        IF NOT EXISTS (
            SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Public Read for user-images'
        ) THEN
            CREATE POLICY "Public Read for user-images" ON storage.objects
            FOR SELECT USING (bucket_id = 'user-images');
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Public Upload for user-images'
        ) THEN
            CREATE POLICY "Public Upload for user-images" ON storage.objects
            FOR INSERT WITH CHECK (bucket_id = 'user-images');
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Public Update for user-images'
        ) THEN
            CREATE POLICY "Public Update for user-images" ON storage.objects
            FOR UPDATE USING (bucket_id = 'user-images');
        END IF;
    END IF;
END $$;
"""

SQL_SEED_DATA = """
-- Initial Seed for Categories
INSERT INTO public.categories (name, slug, description, icon) VALUES
('Electronics & Gadgets', 'electronics', 'Smart devices, headphones, and power banks', '📱'),
('Fresh Grocery', 'grocery', 'Daily essential fresh fruits and vegetables', '🥦'),
('Fashion & Apparel', 'fashion', 'Trendy casual and traditional wear', '👕'),
('Home & Kitchen', 'home', 'Kitchen appliances and modern decor', '🏠')
ON CONFLICT (slug) DO NOTHING;

-- Initial Seed for Vendors
INSERT INTO public.vendors (shop_name, owner_name, phone, address, commission_pct, status, rating) VALUES
('Dhaka Gadget Hub', 'Rahim Uddin', '+8801711001122', 'Mirpur-10, Dhaka', 8.5, 'active', 4.9),
('Green Fresh Grocery', 'Karim Mia', '+8801811223344', 'Uttara Sector-7, Dhaka', 5.0, 'active', 4.8),
('Fashion Fusion BD', 'Nusrat Jahan', '+8801911334455', 'Dhanmondi 27, Dhaka', 10.0, 'active', 4.7)
ON CONFLICT DO NOTHING;

-- Initial Seed for Riders
INSERT INTO public.riders (name, phone, vehicle_type, vehicle_plate, rating, status, total_deliveries) VALUES
('Tariqul Islam', '+8801611009988', 'Motorbike', 'DH-MET-54321', 4.9, 'available', 142),
('Shakil Ahmed', '+8801511223344', 'Bicycle', 'DH-CYC-12345', 4.8, 'on_delivery', 98),
('Mahmudul Hasan', '+8801711998877', 'Motorbike', 'DH-MET-98765', 5.0, 'available', 215)
ON CONFLICT DO NOTHING;

-- Initial Seed for Coupons
INSERT INTO public.coupons (code, discount_pct, discount_flat, min_order_value, max_discount) VALUES
('WELCOME10', 10.0, 0.0, 200.0, 100.0),
('FLAT50', 0.0, 50.0, 500.0, 50.0),
('EIDSPECIAL', 15.0, 0.0, 1000.0, 300.0)
ON CONFLICT (code) DO NOTHING;
"""

def run_migrations():
    """
    Executes all table creation DDL, security policies, and seed data
    against the configured DATABASE_URL.
    """
    db_url = get_database_url()
    if not db_url:
        return {
            "success": False,
            "configured": False,
            "error": "DATABASE_URL is not set in environment.",
            "note": "Configure DATABASE_URL in Render environment variables."
        }

    conn, driver_or_err = get_postgres_connection()
    if conn is None:
        return {
            "success": False,
            "configured": True,
            "error": f"Failed to connect: {driver_or_err}",
            "database_url_masked": db_url[:12] + "..." if len(db_url) > 12 else "***"
        }

    driver_name = driver_or_err
    created_tables = []
    errors = []

    try:
        if driver_name == "psycopg2":
            with conn.cursor() as cur:
                # 1. Create tables
                cur.execute(SQL_CREATE_ALL_TABLES)
                # 2. Add policies and storage bucket
                cur.execute(SQL_POLICIES_AND_BUCKET)
                # 3. Seed data
                cur.execute(SQL_SEED_DATA)

                # 4. Count existing tables in public schema
                cur.execute("""
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    ORDER BY table_name;
                """)
                rows = cur.fetchall()
                created_tables = [r[0] for r in rows]
            conn.close()

        elif driver_name == "pg8000":
            # pg8000 native connection
            conn.run(SQL_CREATE_ALL_TABLES)
            conn.run(SQL_POLICIES_AND_BUCKET)
            conn.run(SQL_SEED_DATA)

            rows = conn.run("""
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'public' 
                ORDER BY table_name;
            """)
            created_tables = [r[0] for r in rows]
            conn.close()

        return {
            "success": True,
            "configured": True,
            "driver": driver_name,
            "message": f"Successfully initialized {len(created_tables)} tables in PostgreSQL database via server!",
            "total_tables": len(created_tables),
            "tables": created_tables,
            "metadata": TABLES_METADATA
        }

    except Exception as exec_err:
        try:
            conn.close()
        except Exception:
            pass
        return {
            "success": False,
            "configured": True,
            "error": f"Migration execution error: {str(exec_err)}",
            "driver": driver_name
        }

def get_database_status_and_tables():
    """Returns the current connection status and row counts of all tables."""
    db_url = get_database_url()
    if not db_url:
        return {
            "configured": False,
            "mode": "sqlite_fallback",
            "message": "DATABASE_URL not set. Running with local SQLite orders.db."
        }

    conn, driver_or_err = get_postgres_connection()
    if conn is None:
        return {
            "configured": True,
            "connected": False,
            "error": driver_or_err,
            "mode": "sqlite_fallback"
        }

    driver_name = driver_or_err
    table_counts = {}
    table_list = []

    try:
        if driver_name == "psycopg2":
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    ORDER BY table_name;
                """)
                table_list = [r[0] for r in cur.fetchall()]

                for t in table_list:
                    try:
                        cur.execute(f"SELECT COUNT(*) FROM public.{t};")
                        table_counts[t] = cur.fetchone()[0]
                    except Exception:
                        table_counts[t] = 0
            conn.close()

        elif driver_name == "pg8000":
            rows = conn.run("""
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'public' 
                ORDER BY table_name;
            """)
            table_list = [r[0] for r in rows]
            for t in table_list:
                try:
                    c_rows = conn.run(f"SELECT COUNT(*) FROM public.{t};")
                    table_counts[t] = c_rows[0][0] if c_rows else 0
                except Exception:
                    table_counts[t] = 0
            conn.close()

        return {
            "configured": True,
            "connected": True,
            "driver": driver_name,
            "total_tables": len(table_list),
            "tables": table_list,
            "counts": table_counts
        }

    except Exception as err:
        try:
            conn.close()
        except Exception:
            pass
        return {
            "configured": True,
            "connected": False,
            "error": str(err),
            "mode": "sqlite_fallback"
        }
